In [37]:
import os
import pandas as pd

# Define the folder path
directory = '/Users/Anubha/Library/CloudStorage/OneDrive-DrexelUniversity/Anubha & Dr. T - Shared/Urban Regulatory projects/Urban Final'
folder_path = f"{directory}/Output/Matching Urban to Drexel"
output_path = f"{directory}/Output/Match Rate"

# Initialize lists to store unmatched section codes and their corresponding states
unmatched_sections = []

# Function to extract parent section code and subsection
def get_parent_and_subsection(section_code):
    parts = section_code.split('(')
    parent_section = parts[0].strip()
    subsection = '(' + '('.join(parts[1:]) if len(parts) > 1 else ''
    return parent_section, subsection

# Iterate through all files in the folder
for file_name in os.listdir(folder_path):
    if file_name.endswith(".xlsx"):
        # Read the Excel file
        file_path = os.path.join(folder_path, file_name)
        df = pd.read_excel(file_path, engine='openpyxl')  # Use openpyxl engine for reading Excel files
        
        # Check for unmatched section codes
        unmatched_df = df[df['section'].isna()]
        unmatched_df = unmatched_df.dropna(subset=['Section Code'])
        
        # If there are unmatched section codes, append them to the list along with the corresponding state
        if not unmatched_df.empty:
            state = file_name.split('_')[-1].split('.')[0].capitalize()
            for code in unmatched_df['Section Code']:
                if isinstance(code, str):  # Ensure the code is a string
                    parent_section, subsection = get_parent_and_subsection(code)
                    unmatched_sections.append((state, parent_section, subsection))

# Create a DataFrame to store the results
results_df = pd.DataFrame(unmatched_sections, columns=['State', 'Primary Section', 'Subsection'])

# Group by state and primary section, and aggregate subsections
grouped_df = results_df.groupby(['State', 'Primary Section'])['Subsection'].apply(lambda x: ', '.join(sorted(set(x)))).reset_index()

# Sort the DataFrame by the "State" and "Primary Section" columns
grouped_df = grouped_df.sort_values(by=['State', 'Primary Section'])

# # Write the DataFrame to an Excel file
grouped_df.to_excel(f'{output_path}/Unmatched Section List.xlsx', index=False)

In [33]:
# Display the results
grouped_df.tail(50)

,State,Primary Section,Subsection
382,Texas,303.052,
383,Utah,13-22-1,
384,Utah,13-22-15,
385,Utah,13-22-17,
386,Utah,13-22-22,
387,Utah,13-22-5,
388,Utah,13-22-8,"(1), (1)(a), (1)(d), (1)(f), (1)(j), (l)(k)"
389,Utah,13-22-9,
390,Utah,75-7-706,
391,Virginia,2.2-507.1,
392,Virginia,55-531,
393,Virginia,55-532,
394,Virginia,57-48,
395,Virginia,57-49,", (A)"
396,Virginia,57-54,
397,Virginia,57-55.2,
398,Virginia,57-55.3,
399,Virginia,57-58,
400,Virginia,57-60,"(A)(1), (A)(3), (A)(4), (A)(7), (A)(8)"
401,Virginia,57-61,
402,Virginia,57-61.2,
403,Virginia,58.1-609.11,(C)(4)
404,Virginia,64.2-759,
405,Washington,11.110.120,
406,Washington,11.96A.030,
407,Washington,19.09.010,
408,Washington,19.09.020,", (2), (2)RCWA"
409,Washington,19.09.068,
410,Washington,19.09.075,
411,Washington,19.09.079,
412,Washington,19.09.081,"(1), (2)"
413,Washington,19.09.097,
414,Washington,19.09.100,
415,Washington,19.09.191,
416,Washington,19.09.210,
417,Washington,434-120-100,
418,Washington,70.45.010,
419,Washington,70.45.060,
420,West-virginia,29-19-1,
421,West-virginia,29-19-5,", (a), (a)(6)(A)"
422,West-virginia,29-19-6,"(1), (2), (3), (4), (5), (6), (7)"
423,West-virginia,29-19-7,
424,West-virginia,29-19-8,
425,West-virginia,29-19-9,
426,West-virginia,44D-7-706,
427,Wisconsin,202.12,", (1)(a), (5)(a)(1), (5)(a)(2), (5)(a)(3), (5)..."
428,Wisconsin,202.13,
429,Wisconsin,202.14,", (11), (3)"
430,Wisconsin,202.15,
431,Wisconsin,701.0706,